apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: op-connect-token
  namespace: onepassword
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    token: AgAKrZl0UWVOgJAvqh2uTF12I13AUTGFTvHWLxIM6wD5SkHyfIW5RhCNWuzh1sYlu/0Sx1BUqHwLBLCszw35oXSgLMjcWIxZjNJt8inVh652WXfqqg8lTz6jvw6d3nBDNqE4X7NOJ8iHqTF2wd6sxrn7hTMlfZXlySixvrOLzr36CY0zoYkACQJdVL0hWrKja50EiPNitiDIUPA5AKGBAe4mIuR56fG7SpO1mJzDSibyEGWQqro0Ze1/Ht8ZBg5lQeUBbo2ZORYefUJMCCa6UtpcE2+dJM+4IjMB74qJLyM7YM3Y3mD+4TmjnvHggp6Qa3JwZd27tSeacShDpzpIP6YqUNeHn1OOeKq3Lu8oD9D/malt/yQeiAhsKbaQr4Zkx3sQRsmz2u0wj4U7zIm8BgxX7mzaY4Zwfkwxrt5cwA7YD4y0SH4q7fuhBEkY/1szYCFftxrrgVAgqU2MrICaXef5G4iCbM8BhesQPX9rhlXCkqwGNO7QK8v7fIT8UyJhqMLMDfyqaqtHbTCfXRoqfD9JYrlOM31PdnCTNmMBUh3jalCMzAdmJkD+Ao1+vmDYrw4s9n1AfTT0LdMozCgb4wKybBwrFvDOySjftu4HFco2uBHLNn0KuD66u/oQKojJbe63+KeTPMBGOqvY/qhadxcHXW7AlBSa2hfjBqiSvLzMUG1ZZ1Sdh7QtzcMOzSvUmjQ=
  template:
    metadata:
      name: op-connect-token
      namespace: onepassword
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
