apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-token
  namespace: cloudflare
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    token: AgB/lwanGgM2aHgu5zlkyn0zEDYIEsjtjcP9v9+Hw1ZScO0nHt5VnmxlSdZzuDyyvwWFPqjzL5/Ia3Zu2u7BnGIJRFOjO/chfPFv5UEW60K+qtstuu2EIc2B6MOB7jRmjZ3+lFQeNs52rl7ds53Yb+BNQYcgMcNQP8LfRw4BMS9vMRuvXThVKowC4OfipQTaB8tWlmn5HGV4BdnVYQ4WZZmJZWIYCUKl6NTR6KxKMfscA4DR5tj1qLPKbawebgj+byNgKUeL+2POdl2BTgv0d8xctkBhmQ6gte0Sqila/1Z4YDbBMEHPWFaZ+ePai2LHZ5fT+/QCzaI4FJHCceE3U2v+Qk1lxKBsZ4DMJNNsYtdx3pBp1fGjMFg50uPip6jczQO2aXOO1YOr88arNVxppp2BYPepE2Mlv03ZjOVHRYAMHCXmimOVrXx+z0kJ0wpV3xakp3h27qqajv/IgbXD3aUeVHS4pI4/LfcH80YE6ueYsXpQNq+dU9r8qtXhgLuzFHbsyBKrG76rFOZxVtjO5EeyYb/HQjqYU4Ac45mfB46t7CyPyy4lwKzq9kfmxBSYUgwXewMkx1iA+toMN90mJnaXCUdZUxKUKxrSCISoWrO16F8JUU4VMsp5rG+PPRHprGl1wl4ONjeT1ENTw6dF63NWSkf/MLagb+9e4flMIXsCOaryXxpwj23ZdTZyT/fG1p+6CvWCjAZWHPCzLBqfSwmXppf+Qb3NLcB6xhb9FhkVV/rIDNFxDwbsKBhQlKIOkYVT+3Yd1Kp6nlwJw3bkHGn+KMSuBpgxAIRwcrcRhT7EZx7AwmSYwhL4VlwFUc+FoUhvNac9NDvjE9XrZe/3IJ+IrkxcPHtqCso+G/4snvAFzjXFYu8EtkKfPlO7dbRh6XrtnPk7VcgX9SDAGCugZZPYxZwtkGq+4TLsn/gc4gY7QeGosBjrtqsW
  template:
    metadata:
      name: cloudflare-tunnel-token
      namespace: cloudflare
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
